# Generated by Django 6.1 on 2026-09-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_detection_species_id_alter_grain_species_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.SlugField(max_length=32, primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(max_length=100, unique=True)),
                ('common_name', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('season', models.CharField(blank=True, default='', max_length=100)),
                ('risk_level', models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], default='Moderate', max_length=10)),
                ('color', models.CharField(max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['sort_order'],
            },
        ),
    ]
