# Generated by Django 6.1 on 2026-09-24 04:18

from django.db import migrations, models


def forwards(apps, schema_editor):
    Report = apps.get_model('reports', 'Report')
    Species = apps.get_model('reports', 'Species')
    # 'Processing' was defined but never written by the app; anything that has
    # it (e.g. hand-edited in admin) becomes the new not-yet-finalised state.
    Report.objects.filter(status='Processing').update(status='Pending')
    # Every species was seeded as 'Moderate' before any real risk data existed.
    # Rows nobody has filled in yet (no common name) are marked honestly.
    Species.objects.filter(risk_level='Moderate', common_name='').update(risk_level='Not assessed')


def backwards(apps, schema_editor):
    Report = apps.get_model('reports', 'Report')
    Species = apps.get_model('reports', 'Species')
    Report.objects.filter(status='Pending').update(status='Processing')
    Species.objects.filter(risk_level='Not assessed').update(risk_level='Moderate')


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_recolor_species'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={'ordering': ['-grain_count', '-avg_confidence']},
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Needs review', 'Needs review')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='species',
            name='risk_level',
            field=models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low'), ('Not assessed', 'Not assessed')], default='Not assessed', max_length=16),
        ),
        migrations.RunPython(forwards, backwards),
    ]
