# Generated by Django 6.1 on 2026-09-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_lifecycle_and_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sample_detections',
            field=models.BooleanField(default=False),
        ),
    ]
