# Generated by Django 6.1 on 2026-08-30 16:54

import django.core.validators
import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('collected_at', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}-\\d{2}(T\\d{2}:\\d{2})?$', 'collectedAt must be "YYYY-MM-DD" or "YYYY-MM-DDTHH:mm".')])),
                ('location', models.CharField(max_length=255)),
                ('researcher', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Processing', 'Processing'), ('Needs review', 'Needs review')], default='Completed', max_length=20)),
                ('weather_condition', models.CharField(blank=True, choices=[('Sunny', 'Sunny'), ('Partly cloudy', 'Partly cloudy'), ('Overcast', 'Overcast'), ('Rainy', 'Rainy'), ('Windy', 'Windy')], max_length=20, null=True)),
                ('weather_temperature_c', models.FloatField(blank=True, null=True)),
                ('weather_humidity_pct', models.FloatField(blank=True, null=True)),
                ('weather_wind_kph', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collected_at', '-sample_id'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=reports.models.slide_image_upload_to)),
                ('notes', models.TextField(blank=True, default='')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='reports.report')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('species_id', models.CharField(choices=[('poaceae', 'Poaceae'), ('betula', 'Betula'), ('alnus', 'Alnus'), ('corylus', 'Corylus'), ('quercus', 'Quercus'), ('ambrosia', 'Ambrosia'), ('pinus', 'Pinus'), ('artemisia', 'Artemisia')], max_length=20)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('box_x', models.FloatField()),
                ('box_y', models.FloatField()),
                ('box_width', models.FloatField()),
                ('box_height', models.FloatField()),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grains', to='reports.slide')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.CharField(choices=[('poaceae', 'Poaceae'), ('betula', 'Betula'), ('alnus', 'Alnus'), ('corylus', 'Corylus'), ('quercus', 'Quercus'), ('ambrosia', 'Ambrosia'), ('pinus', 'Pinus'), ('artemisia', 'Artemisia')], max_length=20)),
                ('grain_count', models.PositiveIntegerField()),
                ('avg_confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='reports.slide')),
            ],
        ),
        migrations.AddConstraint(
            model_name='slide',
            constraint=models.UniqueConstraint(fields=('report', 'number'), name='unique_slide_number_per_report'),
        ),
        migrations.AddConstraint(
            model_name='grain',
            constraint=models.UniqueConstraint(fields=('slide', 'number'), name='unique_grain_number_per_slide'),
        ),
        migrations.AddConstraint(
            model_name='detection',
            constraint=models.UniqueConstraint(fields=('slide', 'species_id'), name='unique_species_per_slide'),
        ),
    ]
