# Generated by Django 6.1 on 2026-08-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='species_id',
            field=models.CharField(choices=[('amaranthus_spinosus', 'Amaranthus spinosus'), ('axonopus_compressus', 'Axonopus compressus'), ('brachiaria_mutica', 'Brachiaria mutica'), ('chloris_barbata', 'Chloris barbata'), ('chrysopogon_aciculatus', 'Chrysopogon aciculatus'), ('cocos_nucifera', 'Cocos nucifera'), ('cyperus_rotundus', 'Cyperus rotundus'), ('dactyloctenium_aegyptium', 'Dactyloctenium aegyptium'), ('digitaria_ciliaris', 'Digitaria ciliaris'), ('echinochloa_crus_galli', 'Echinochloa crus-galli'), ('eleusine_indica', 'Eleusine indica'), ('imperata_cylindrica', 'Imperata cylindrica'), ('leucaena_leucocephala', 'Leucaena leucocephala'), ('panicum_maximum', 'Panicum maximum'), ('pennisetum_polystachion', 'Pennisetum polystachion'), ('pithecellobium_dulce', 'Pithecellobium dulce'), ('saccharum_spontaneum', 'Saccharum spontaneum'), ('samanea_saman', 'Samanea saman'), ('sorghum_halepense', 'Sorghum halepense'), ('tridax_procumbens', 'Tridax procumbens'), ('oryza_sativa', 'Oryza sativa'), ('mimosa_pudica', 'Mimosa pudica'), ('mangifera_indica', 'Mangifera indica')], max_length=32),
        ),
        migrations.AlterField(
            model_name='grain',
            name='species_id',
            field=models.CharField(choices=[('amaranthus_spinosus', 'Amaranthus spinosus'), ('axonopus_compressus', 'Axonopus compressus'), ('brachiaria_mutica', 'Brachiaria mutica'), ('chloris_barbata', 'Chloris barbata'), ('chrysopogon_aciculatus', 'Chrysopogon aciculatus'), ('cocos_nucifera', 'Cocos nucifera'), ('cyperus_rotundus', 'Cyperus rotundus'), ('dactyloctenium_aegyptium', 'Dactyloctenium aegyptium'), ('digitaria_ciliaris', 'Digitaria ciliaris'), ('echinochloa_crus_galli', 'Echinochloa crus-galli'), ('eleusine_indica', 'Eleusine indica'), ('imperata_cylindrica', 'Imperata cylindrica'), ('leucaena_leucocephala', 'Leucaena leucocephala'), ('panicum_maximum', 'Panicum maximum'), ('pennisetum_polystachion', 'Pennisetum polystachion'), ('pithecellobium_dulce', 'Pithecellobium dulce'), ('saccharum_spontaneum', 'Saccharum spontaneum'), ('samanea_saman', 'Samanea saman'), ('sorghum_halepense', 'Sorghum halepense'), ('tridax_procumbens', 'Tridax procumbens'), ('oryza_sativa', 'Oryza sativa'), ('mimosa_pudica', 'Mimosa pudica'), ('mangifera_indica', 'Mangifera indica')], max_length=32),
        ),
    ]
