# Generated by Django 6.1 on 2026-09-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_sample_detections'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='species',
            name='distribution',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='species',
            name='family',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='species',
            name='filipino_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='growth_form',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='info_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='species',
            name='photo_credit',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='species',
            name='photo_license',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='species',
            name='photo_source',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='species',
            name='photo_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='species',
            name='pollination',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
